#############################################################################
# Makefile for building: opengazer
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  opengazer.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile opengazer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe `pkg-config opencv --cflags` -include Prefix.hpp -O2 -D_REENTRANT -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe `pkg-config opencv --cflags` -include Prefix.hpp -O2 -D_REENTRANT -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 `pkg-config opencv --libs` -L/usr/local/lib -L/opt/local/lib -lm -ldl -lgthread-2.0 -lfann -lX11 -lXtst -lboost_filesystem -lboost_system -lgsl -lgslcblas -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = opengazer.cpp \
		Calibrator.cpp \
		HeadTracker.cpp \
		LeastSquares.cpp \
		EyeExtractor.cpp \
		GazeTracker.cpp \
		MainGazeTracker.cpp \
		OutputMethods.cpp \
		PointTracker.cpp \
		FaceDetector.cpp \
		Point.cpp \
		utils.cpp \
		BlinkDetector.cpp \
		FeatureDetector.cpp \
		mir.cpp \
		DebugWindow.cpp \
		Application.cpp \
		Video.cpp \
		AnchorPointSelector.cpp \
		Command.cpp \
		ImageWindow.cpp \
		ImageWidget.cpp \
		TestWindow.cpp \
		HiResTimer.cpp \
		EyeCenterDetector.cpp \
		GoogleGlassWindow.cpp \
		EyeExtractorSegmentationGroundTruth.cpp \
		FrogGame.cpp \
		HistogramFeatureExtractor.cpp \
		PointTrackerWithTemplate.cpp \
		GazeTrackerHistogramFeatures.cpp \
		Configuration.cpp \
		MoveMouse.cpp \
		Scroll.cpp moc_MainGazeTracker.cpp \
		moc_ImageWidget.cpp
OBJECTS       = opengazer.o \
		Calibrator.o \
		HeadTracker.o \
		LeastSquares.o \
		EyeExtractor.o \
		GazeTracker.o \
		MainGazeTracker.o \
		OutputMethods.o \
		PointTracker.o \
		FaceDetector.o \
		Point.o \
		utils.o \
		BlinkDetector.o \
		FeatureDetector.o \
		mir.o \
		DebugWindow.o \
		Application.o \
		Video.o \
		AnchorPointSelector.o \
		Command.o \
		ImageWindow.o \
		ImageWidget.o \
		TestWindow.o \
		HiResTimer.o \
		EyeCenterDetector.o \
		GoogleGlassWindow.o \
		EyeExtractorSegmentationGroundTruth.o \
		FrogGame.o \
		HistogramFeatureExtractor.o \
		PointTrackerWithTemplate.o \
		GazeTrackerHistogramFeatures.o \
		Configuration.o \
		MoveMouse.o \
		Scroll.o \
		moc_MainGazeTracker.o \
		moc_ImageWidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		opengazer.pro opengazer.cpp \
		Calibrator.cpp \
		HeadTracker.cpp \
		LeastSquares.cpp \
		EyeExtractor.cpp \
		GazeTracker.cpp \
		MainGazeTracker.cpp \
		OutputMethods.cpp \
		PointTracker.cpp \
		FaceDetector.cpp \
		Point.cpp \
		utils.cpp \
		BlinkDetector.cpp \
		FeatureDetector.cpp \
		mir.cpp \
		DebugWindow.cpp \
		Application.cpp \
		Video.cpp \
		AnchorPointSelector.cpp \
		Command.cpp \
		ImageWindow.cpp \
		ImageWidget.cpp \
		TestWindow.cpp \
		HiResTimer.cpp \
		EyeCenterDetector.cpp \
		GoogleGlassWindow.cpp \
		EyeExtractorSegmentationGroundTruth.cpp \
		FrogGame.cpp \
		HistogramFeatureExtractor.cpp \
		PointTrackerWithTemplate.cpp \
		GazeTrackerHistogramFeatures.cpp \
		Configuration.cpp \
		MoveMouse.cpp \
		Scroll.cpp
QMAKE_TARGET  = opengazer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = opengazer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: opengazer.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		opengazer.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile opengazer.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
opengazer.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile opengazer.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/opengazer1.0.0 || mkdir -p .tmp/opengazer1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/opengazer1.0.0/ && $(COPY_FILE) --parents Calibrator.h HeadTracker.h LeastSquares.h EyeExtractor.h GazeTracker.h MainGazeTracker.h OutputMethods.h PointTracker.h FaceDetector.h Point.h utils.h BlinkDetector.h FeatureDetector.h mir.h DebugWindow.h Application.h Video.h AnchorPointSelector.h Command.h ImageWindow.h ImageWidget.h TestWindow.h Prefix.hpp HiResTimer.h EyeCenterDetector.h GoogleGlassWindow.h EyeExtractorSegmentationGroundTruth.h FrogGame.h HistogramFeatureExtractor.h PointTrackerWithTemplate.h GazeTrackerHistogramFeatures.h Component.h Configuration.h MoveMouse.h Scroll.h .tmp/opengazer1.0.0/ && $(COPY_FILE) --parents opengazer.cpp Calibrator.cpp HeadTracker.cpp LeastSquares.cpp EyeExtractor.cpp GazeTracker.cpp MainGazeTracker.cpp OutputMethods.cpp PointTracker.cpp FaceDetector.cpp Point.cpp utils.cpp BlinkDetector.cpp FeatureDetector.cpp mir.cpp DebugWindow.cpp Application.cpp Video.cpp AnchorPointSelector.cpp Command.cpp ImageWindow.cpp ImageWidget.cpp TestWindow.cpp HiResTimer.cpp EyeCenterDetector.cpp GoogleGlassWindow.cpp EyeExtractorSegmentationGroundTruth.cpp FrogGame.cpp HistogramFeatureExtractor.cpp PointTrackerWithTemplate.cpp GazeTrackerHistogramFeatures.cpp Configuration.cpp MoveMouse.cpp Scroll.cpp .tmp/opengazer1.0.0/ && (cd `dirname .tmp/opengazer1.0.0` && $(TAR) opengazer1.0.0.tar opengazer1.0.0 && $(COMPRESS) opengazer1.0.0.tar) && $(MOVE) `dirname .tmp/opengazer1.0.0`/opengazer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/opengazer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_MainGazeTracker.cpp moc_ImageWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainGazeTracker.cpp moc_ImageWidget.cpp
moc_MainGazeTracker.cpp: EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Component.h \
		Point.h \
		PointTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		Video.h \
		Command.h \
		MainGazeTracker.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/maikon/workspace/gazetetraplegic -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainGazeTracker.h -o moc_MainGazeTracker.cpp

moc_ImageWidget.cpp: ImageWidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/maikon/workspace/gazetetraplegic -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ImageWidget.h -o moc_ImageWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

opengazer.o: opengazer.cpp MainGazeTracker.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Component.h \
		Point.h \
		PointTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		Video.h \
		Command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opengazer.o opengazer.cpp

Calibrator.o: Calibrator.cpp Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Point.h \
		Component.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Calibrator.o Calibrator.cpp

HeadTracker.o: HeadTracker.cpp HeadTracker.h \
		PointTracker.h \
		Point.h \
		Component.h \
		FMatrixAffineCompute.cpp \
		utils.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HeadTracker.o HeadTracker.cpp

LeastSquares.o: LeastSquares.cpp LeastSquares.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LeastSquares.o LeastSquares.cpp

EyeExtractor.o: EyeExtractor.cpp EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Component.h \
		Point.h \
		PointTracker.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EyeExtractor.o EyeExtractor.cpp

GazeTracker.o: GazeTracker.cpp GazeTracker.h \
		utils.h \
		Point.h \
		GaussianProcess.cpp \
		Component.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		mir.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GazeTracker.o GazeTracker.cpp

MainGazeTracker.o: MainGazeTracker.cpp MainGazeTracker.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Component.h \
		Point.h \
		PointTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		Video.h \
		Command.h \
		HeadTracker.h \
		EyeCenterDetector.h \
		HistogramFeatureExtractor.h \
		PointTrackerWithTemplate.h \
		GazeTrackerHistogramFeatures.h \
		FrogGame.h \
		MoveMouse.h \
		Application.h \
		Configuration.h \
		DebugWindow.h \
		TestWindow.h \
		Scroll.h \
		FaceDetector.h \
		AnchorPointSelector.h \
		HiResTimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainGazeTracker.o MainGazeTracker.cpp

OutputMethods.o: OutputMethods.cpp OutputMethods.h \
		GazeTracker.h \
		utils.h \
		Point.h \
		GaussianProcess.cpp \
		Component.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Application.h \
		Configuration.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OutputMethods.o OutputMethods.cpp

PointTracker.o: PointTracker.cpp PointTracker.h \
		Point.h \
		Component.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h \
		FaceDetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PointTracker.o PointTracker.cpp

FaceDetector.o: FaceDetector.cpp FaceDetector.h \
		utils.h \
		Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FaceDetector.o FaceDetector.cpp

Point.o: Point.cpp Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Point.o Point.cpp

utils.o: utils.cpp utils.h \
		Point.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		GaussianProcess.cpp \
		Component.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

BlinkDetector.o: BlinkDetector.cpp BlinkDetector.h \
		FeatureDetector.h \
		EyeExtractor.h \
		Component.h \
		Point.h \
		PointTracker.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlinkDetector.o BlinkDetector.cpp

FeatureDetector.o: FeatureDetector.cpp FeatureDetector.h \
		utils.h \
		Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FeatureDetector.o FeatureDetector.cpp

mir.o: mir.cpp mir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mir.o mir.cpp

DebugWindow.o: DebugWindow.cpp DebugWindow.h \
		ImageWindow.h \
		ImageWidget.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		Point.h \
		GaussianProcess.cpp \
		Component.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		Command.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DebugWindow.o DebugWindow.cpp

Application.o: Application.cpp Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		Point.h \
		GaussianProcess.cpp \
		Component.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Application.o Application.cpp

Video.o: Video.cpp Video.h \
		HiResTimer.h \
		utils.h \
		Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Video.o Video.cpp

AnchorPointSelector.o: AnchorPointSelector.cpp AnchorPointSelector.h \
		Point.h \
		Component.h \
		PointTracker.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnchorPointSelector.o AnchorPointSelector.cpp

Command.o: Command.cpp Command.h \
		utils.h \
		Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Command.o Command.cpp

ImageWindow.o: ImageWindow.cpp ImageWindow.h \
		ImageWidget.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		Point.h \
		GaussianProcess.cpp \
		Component.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageWindow.o ImageWindow.cpp

ImageWidget.o: ImageWidget.cpp ImageWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageWidget.o ImageWidget.cpp

TestWindow.o: TestWindow.cpp TestWindow.h \
		ImageWindow.h \
		ImageWidget.h \
		Point.h \
		Component.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		Command.h \
		DebugWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TestWindow.o TestWindow.cpp

HiResTimer.o: HiResTimer.cpp HiResTimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HiResTimer.o HiResTimer.cpp

EyeCenterDetector.o: EyeCenterDetector.cpp EyeCenterDetector.h \
		Component.h \
		Point.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EyeCenterDetector.o EyeCenterDetector.cpp

GoogleGlassWindow.o: GoogleGlassWindow.cpp GoogleGlassWindow.h \
		ImageWindow.h \
		ImageWidget.h \
		Point.h \
		Component.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GoogleGlassWindow.o GoogleGlassWindow.cpp

EyeExtractorSegmentationGroundTruth.o: EyeExtractorSegmentationGroundTruth.cpp EyeExtractorSegmentationGroundTruth.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Component.h \
		Point.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EyeExtractorSegmentationGroundTruth.o EyeExtractorSegmentationGroundTruth.cpp

FrogGame.o: FrogGame.cpp FrogGame.h \
		GazeTracker.h \
		utils.h \
		Point.h \
		GaussianProcess.cpp \
		Component.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		ImageWindow.h \
		ImageWidget.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FrogGame.o FrogGame.cpp

HistogramFeatureExtractor.o: HistogramFeatureExtractor.cpp HistogramFeatureExtractor.h \
		utils.h \
		Point.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		Component.h \
		PointTracker.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		GaussianProcess.cpp \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HistogramFeatureExtractor.o HistogramFeatureExtractor.cpp

PointTrackerWithTemplate.o: PointTrackerWithTemplate.cpp PointTrackerWithTemplate.h \
		utils.h \
		Point.h \
		Component.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PointTrackerWithTemplate.o PointTrackerWithTemplate.cpp

GazeTrackerHistogramFeatures.o: GazeTrackerHistogramFeatures.cpp GazeTrackerHistogramFeatures.h \
		utils.h \
		Point.h \
		GaussianProcess.cpp \
		Component.h \
		HistogramFeatureExtractor.h \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		mir.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GazeTrackerHistogramFeatures.o GazeTrackerHistogramFeatures.cpp

Configuration.o: Configuration.cpp Configuration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Configuration.o Configuration.cpp

MoveMouse.o: MoveMouse.cpp MoveMouse.h \
		Component.h \
		Point.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MoveMouse.o MoveMouse.cpp

Scroll.o: Scroll.cpp Scroll.h \
		Component.h \
		Point.h \
		Application.h \
		Configuration.h \
		OutputMethods.h \
		GazeTracker.h \
		utils.h \
		GaussianProcess.cpp \
		EyeExtractor.h \
		BlinkDetector.h \
		FeatureDetector.h \
		PointTracker.h \
		Video.h \
		MainGazeTracker.h \
		Calibrator.h \
		ImageWindow.h \
		ImageWidget.h \
		Command.h \
		DebugWindow.h \
		TestWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scroll.o Scroll.cpp

moc_MainGazeTracker.o: moc_MainGazeTracker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainGazeTracker.o moc_MainGazeTracker.cpp

moc_ImageWidget.o: moc_ImageWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageWidget.o moc_ImageWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

